.PHONY: get-config set-controller-role

get-config:
	@ryu-manager  get-config.py

set-controller-role-test:
	@ryu-manager  set-controller-role-test.py

set-inexistent-queue-config-test:
	@ryu-manager set-inexistent-queue-config-test.py

set-port-element-of-queue-resource-test:
	@ryu-manager set-port-element-of-queue-resource-test.py

set-queue-min-max-rate-test:
	@ryu-manager set-queue-min-max-rate-test.py
